// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bjdubmdryfjjnvzypfmx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJqZHVibWRyeWZqam52enlwZm14Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQwODk3MzksImV4cCI6MjA0OTY2NTczOX0.yyj-M-Y4HhCkvU5k4JkeixscOgO_uB-z3PslS1AI46U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);